Repository ocp-power-automation/ci-monitoring-automation, pull requests merged in 2023-12, with the labels that each got.

#2 Fix(#1) Update README with new repo name
  README.md
Labels: lgtm, approved

#9 Added support to get job runs based on zone/leases
  CI_DailyBuildUpdates.py
  CI_JobHistory.py
  README.md
  monitor.py
Labels: lgtm, approved, size/M

#12 Fix(#7) Add support for z builds
  CI_DailyBuildUpdates.py
  CI_JobHistory.py
  README.md
  monitor.py
  p_config.json
  z_config.json
Labels: lgtm, approved, size/L

#13 Support to check if specifically mentioned testcases are failing in any of builds
  CI_JobHistory.py
  monitor.py
Labels: lgtm, approved, size/M

#20 Updated OWNERS file
  OWNERS
Labels: lgtm, approved, size/XS

#18 Fix #17 #19: Add support for MCE and SNO jobs
  CI_JobHistory.py
  monitor.py
  p_config.json
Labels: lgtm, approved, size/L
