Repository ocp-power-automation/ci-monitoring-automation, pull requests merged in 2024-01, with the labels that each got.

#22 Fix(#21) Developed function to get all failed testcases from different test suites and store them in a single variable
  CI_JobHistory.py
  monitor.py
Labels: lgtm, approved, size/L

#25 Fix(#6) Add Docstrings for all the functions
  CI_JobHistory.py
  config.ini
  monitor.py
Labels: lgtm, approved, size/L

#28 updated 4.15 powervs links
  p_config.json
Labels: lgtm, approved, size/XS

#30 Fix(#29) Added code to handle xml file parsing errors
  monitor.py
Labels: lgtm, approved, size/S

#27 Added support to print failing testcase with its frequency
  CI_JobHistory.py
  monitor.py
Labels: lgtm, approved, size/M
