Repository ocp-power-automation/ci-monitoring-automation, pull requests merged in 2024-04, with the labels that each got.

#48 Modified get_quota_and_nightly method
  monitor.py
Labels: lgtm, approved, size/L

#50 Fix(#49) Added a function to get job status and made minor changes
  monitor.py
Labels: lgtm, approved, size/L

#51 Added changes to get node status for older ci jobs
  CI_JobHistory.py
  monitor.py
Labels: lgtm, approved, size/M

#53 Added function to check if sensitive information is exposed
  monitor.py
Labels: lgtm, approved, size/M

#55 Added support to get all CIs JobHistory
  CI_JobHistory.py
Labels: lgtm, approved, size/S

#56 Added changes to check node details of compact run
  CI_JobHistory.py
  monitor.py
Labels: lgtm, approved, size/S
