Repository ocp-power-automation/ci-monitoring-automation, pull requests merged in 2024-12, with the labels that each got.

#87 Added agent and 4.19 jobs
  p_auxillary.json
  p_periodic.json
Labels: approved, size/S

#90 changed name of job_platform flag
  CI_JobHistory.py
Labels: lgtm, approved

#88 Added support to get job runs details based on the release
  CI_JobHistory.py
  aggregate.py
  monitor.py
Labels: lgtm, approved

#93 Fix for daily build update
  monitor.py
Labels: lgtm, approved, size/XS
