Repository ocp-power-automation/ci-monitoring-automation, pull requests merged in 2024-03, with the labels that each got.

#41 Fix(#40) Added support for auxiliary jobs and resolved minor bug in tracker script
  CI_DailyBuildUpdates.py
  CI_JobHistory.py
  README.md
  config.ini
  monitor.py
  p_auxillary.json
  p_periodic.json
  tracker.py
  z_periodic.json
Labels: lgtm, approved, size/L

#43 Renamed command line argument ci_arch to builds in tracker.py script
  README.md
  monitor.py
  tracker.py
Labels: lgtm, approved, size/M

#46 Added support for 4.16 Jobs
  monitor.py
  p_periodic.json
Labels: lgtm, approved, size/XS

#45 Changed code to display output if execution of a test suite is aborted
  monitor.py
  tracker.py
Labels: lgtm, approved, size/L

#47 Added symcount variable to get count of failed testcases
  config.ini
  monitor.py
Labels: lgtm, approved, size/XS
